import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ContextProvider from "@/providers/ContextProvider";
import { HandleOnComplete } from "@/lib/router-events";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ContextProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <HandleOnComplete />
          </body>
        </html>
      </ContextProvider>
    </ClerkProvider>
  );
}
