import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ContextProvider from "@/providers/ContextProvider";
import { HandleOnComplete } from "@/lib/router-events";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider allowedRedirectOrigins={["http://ec2-44-204-240-212.compute-1.amazonaws.com/"]}>
      <ContextProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <HandleOnComplete />
            <Analytics />
            <SpeedInsights/>
          </body>
        </html>
      </ContextProvider>
    </ClerkProvider>
  );
}
